[2025-05-13T07:18:41.423+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T07:18:41.445+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_filing_scheduler.set_adc_from_airflow_connection manual__2025-05-13T07:18:17.932048+00:00 [queued]>
[2025-05-13T07:18:41.455+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_filing_scheduler.set_adc_from_airflow_connection manual__2025-05-13T07:18:17.932048+00:00 [queued]>
[2025-05-13T07:18:41.455+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-13T07:18:41.473+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): set_adc_from_airflow_connection> on 2025-05-13 07:18:17.932048+00:00
[2025-05-13T07:18:41.505+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=256) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-13T07:18:41.508+0000] {standard_task_runner.py:72} INFO - Started process 265 to run task
[2025-05-13T07:18:41.508+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_filing_scheduler', 'set_adc_from_***_connection', 'manual__2025-05-13T07:18:17.932048+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/orchestrate_clinical_pipeline.py', '--cfg-path', '/tmp/tmp_rpk_9of']
[2025-05-13T07:18:41.511+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask set_adc_from_***_connection
[2025-05-13T07:18:41.572+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_filing_scheduler.set_adc_from_airflow_connection manual__2025-05-13T07:18:17.932048+00:00 [running]> on host ae64a678dd42
[2025-05-13T07:18:41.680+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_filing_scheduler' AIRFLOW_CTX_TASK_ID='set_adc_from_***_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T07:18:17.932048+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T07:18:17.932048+00:00'
[2025-05-13T07:18:41.681+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T07:18:41.691+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T07:18:41.693+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T07:18:41.695+0000] {logging_mixin.py:190} INFO - GOOGLE_APPLICATION_CREDENTIALS set to: /tmp/tmpe_hbehsn.json
[2025-05-13T07:18:41.696+0000] {python.py:240} INFO - Done. Returned value was: /tmp/tmpe_hbehsn.json
[2025-05-13T07:18:41.738+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T07:18:41.739+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sec_filing_scheduler, task_id=set_adc_from_***_connection, run_id=manual__2025-05-13T07:18:17.932048+00:00, execution_date=20250513T071817, start_date=20250513T071841, end_date=20250513T071841
[2025-05-13T07:18:41.810+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-13T07:18:41.834+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-13T07:18:41.838+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
