[2025-05-13T10:03:59.729+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T10:03:59.754+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T10:03:38.347977+00:00 [queued]>
[2025-05-13T10:03:59.771+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T10:03:38.347977+00:00 [queued]>
[2025-05-13T10:03:59.772+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-13T10:03:59.798+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_wve> on 2025-05-13 10:03:38.347977+00:00
[2025-05-13T10:03:59.855+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1045) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-13T10:03:59.859+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_filing_scheduler', 'process_wve', 'manual__2025-05-13T10:03:38.347977+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/orchestrate_clinical_pipeline.py', '--cfg-path', '/tmp/tmprqmf440r']
[2025-05-13T10:03:59.862+0000] {standard_task_runner.py:72} INFO - Started process 1047 to run task
[2025-05-13T10:03:59.862+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask process_wve
[2025-05-13T10:04:00.003+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T10:03:38.347977+00:00 [running]> on host e8b101d3d861
[2025-05-13T10:04:00.282+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_filing_scheduler' AIRFLOW_CTX_TASK_ID='process_wve' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T10:03:38.347977+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T10:03:38.347977+00:00'
[2025-05-13T10:04:00.285+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T10:04:00.423+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T10:04:00.429+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T10:04:01.647+0000] {logging_mixin.py:190} INFO - Found 135 8-K filings
[2025-05-13T10:04:01.649+0000] {logging_mixin.py:190} INFO - Found 10 10-K filings
[2025-05-13T10:04:01.650+0000] {logging_mixin.py:190} INFO - Found 29 10-Q filings
[2025-05-13T10:04:01.652+0000] {logging_mixin.py:190} INFO - No new filings to process.
[2025-05-13T10:04:01.653+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-13T10:04:01.701+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T10:04:01.702+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sec_filing_scheduler, task_id=process_wve, run_id=manual__2025-05-13T10:03:38.347977+00:00, execution_date=20250513T100338, start_date=20250513T100359, end_date=20250513T100401
[2025-05-13T10:04:01.786+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-13T10:04:01.871+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-13T10:04:01.887+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
