[2025-05-13T09:34:14.783+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T09:34:14.802+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_alny manual__2025-05-13T09:33:48.544323+00:00 [queued]>
[2025-05-13T09:34:14.812+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_alny manual__2025-05-13T09:33:48.544323+00:00 [queued]>
[2025-05-13T09:34:14.813+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-13T09:34:14.833+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_alny> on 2025-05-13 09:33:48.544323+00:00
[2025-05-13T09:34:14.858+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=633) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-13T09:34:14.861+0000] {standard_task_runner.py:72} INFO - Started process 641 to run task
[2025-05-13T09:34:14.875+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_filing_scheduler', 'process_alny', 'manual__2025-05-13T09:33:48.544323+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/orchestrate_clinical_pipeline.py', '--cfg-path', '/tmp/tmpa246kvg6']
[2025-05-13T09:34:14.877+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask process_alny
[2025-05-13T09:34:15.151+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_filing_scheduler.process_alny manual__2025-05-13T09:33:48.544323+00:00 [running]> on host e8b101d3d861
[2025-05-13T09:34:15.464+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_filing_scheduler' AIRFLOW_CTX_TASK_ID='process_alny' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T09:33:48.544323+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T09:33:48.544323+00:00'
[2025-05-13T09:34:15.469+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T09:34:15.752+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T09:34:15.757+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T09:34:17.371+0000] {logging_mixin.py:190} INFO - Found 141 8-K filings
[2025-05-13T09:34:17.372+0000] {logging_mixin.py:190} INFO - Found 13 10-K filings
[2025-05-13T09:34:17.373+0000] {logging_mixin.py:190} INFO - Found 37 10-Q filings
[2025-05-13T09:34:17.375+0000] {logging_mixin.py:190} INFO - Found 191 new filings.
[2025-05-13T09:34:17.376+0000] {logging_mixin.py:190} INFO - Processing 1 filings...
[2025-05-13T09:34:17.387+0000] {logging_mixin.py:190} INFO - Processing filing: 0001178670-25-000052
[2025-05-13T09:34:19.201+0000] {logging_mixin.py:190} INFO - Finished 1/1: 0001178670-25-000052
[2025-05-13T09:34:19.204+0000] {logging_mixin.py:190} INFO - llm_names_grouping None
[2025-05-13T09:34:19.205+0000] {logging_mixin.py:190} INFO - Error processing filings: 'NoneType' object is not subscriptable
[2025-05-13T09:34:19.208+0000] {logging_mixin.py:190} INFO - Deleted output_dir: sec_data/ALNY
[2025-05-13T09:34:19.209+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-13T09:34:19.221+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T09:34:19.222+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sec_filing_scheduler, task_id=process_alny, run_id=manual__2025-05-13T09:33:48.544323+00:00, execution_date=20250513T093348, start_date=20250513T093414, end_date=20250513T093419
[2025-05-13T09:34:19.296+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-13T09:34:19.335+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-13T09:34:19.340+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
