[2025-05-13T07:49:24.588+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T07:49:24.622+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T07:49:04.464039+00:00 [queued]>
[2025-05-13T07:49:24.642+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T07:49:04.464039+00:00 [queued]>
[2025-05-13T07:49:24.643+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-13T07:49:24.667+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_wve> on 2025-05-13 07:49:04.464039+00:00
[2025-05-13T07:49:24.692+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=669) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-13T07:49:24.696+0000] {standard_task_runner.py:72} INFO - Started process 678 to run task
[2025-05-13T07:49:24.705+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_filing_scheduler', 'process_wve', 'manual__2025-05-13T07:49:04.464039+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/orchestrate_clinical_pipeline.py', '--cfg-path', '/tmp/tmpvbf4ws26']
[2025-05-13T07:49:24.711+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask process_wve
[2025-05-13T07:49:24.819+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T07:49:04.464039+00:00 [running]> on host ae64a678dd42
[2025-05-13T07:49:25.027+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_filing_scheduler' AIRFLOW_CTX_TASK_ID='process_wve' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T07:49:04.464039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T07:49:04.464039+00:00'
[2025-05-13T07:49:25.036+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T07:49:25.060+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T07:49:25.080+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T07:49:26.412+0000] {logging_mixin.py:190} INFO - Found 135 8-K filings
[2025-05-13T07:49:26.413+0000] {logging_mixin.py:190} INFO - Found 10 10-K filings
[2025-05-13T07:49:26.413+0000] {logging_mixin.py:190} INFO - Found 29 10-Q filings
[2025-05-13T07:49:26.416+0000] {logging_mixin.py:190} INFO - No new filings to process.
[2025-05-13T07:49:26.422+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-13T07:49:26.472+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T07:49:26.482+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sec_filing_scheduler, task_id=process_wve, run_id=manual__2025-05-13T07:49:04.464039+00:00, execution_date=20250513T074904, start_date=20250513T074924, end_date=20250513T074926
[2025-05-13T07:49:26.729+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-13T07:49:26.783+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
